#include<bits/stdc++.h>
using namespace std;

int power(int n)
{
    int sum =0;
    while(n)
    {
        int r = n%10;
        sum += r;
        n = n/10;
    }
    return  sum;

}

int main()
{
    int t;
    cin>>t;
    while(t--)
    {
        int pc,pr;
        cin>>pc>>pr;
        
        
    }
}

/* 
0 if chef wins
1 if rick wins
second integer for the number of digit of integers generated by the winner
*/

